{% set version = "2.0.0" %}

package:
  name: intake-xarray
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/intake-xarray/intake_xarray-{{ version }}.tar.gz
  sha256: 163ca7aa2206ab43468f962c8c3260a2ef1e4bea388ca3d42c427d9b6b3ce133

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - dask >=2.2
    - fsspec >=2022
    - intake >=0.6.6
    - msgpack-python
    - netcdf4
    - python >=3.5
    - requests
    - xarray >=2022
    - zarr

test:
  imports:
    - intake_xarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/intake/intake-xarray
  license: BSD-2-Clause
  license_file: LICENSE
  summary: xarray plugins for Intake

extra:
  recipe-maintainers:
    - ocefpaf
    - jsignell
    - martindurant
    - weiji14
