{% set version = "0.6.1" %}

package:
  name: intake-xarray
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake-xarray/intake-xarray-{{ version }}.tar.gz
  sha256: 63dc2a8b937d8f956255d8f8641f08ea654b2d9e88687ec3d1ccc66462fabf9e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - intake >=0.5.2
    - dask >=2.2
    - netcdf4
    - xarray >=0.12.0
    - zarr

test:
  imports:
    - intake_xarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ContinuumIO/intake-xarray
  license: BSD-2-Clause
  license_file: LICENSE
  summary: xarray plugins for Intake

extra:
  recipe-maintainers:
    - ocefpaf
    - jsignell
    - martindurant
    - weiji14
