{% set version = "0.3.1" %}

package:
   name: intake-xarray
   version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake-xarray/intake-xarray-{{ version }}.tar.gz
  sha256: cb284d6346b6e8fb6752a1fe616e594ad3c1ed50ffd336bbe8d07cd8d5ea9de4

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - intake >=0.4.1
    - xarray >=0.11.0
    - zarr
    - dask
    - netcdf4

test:
  imports:
    - intake_xarray

about:
  home: https://github.com/ContinuumIO/intake-xarray
  license: BSD-2-Clause
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: xarray plugins for Intake

extra:
  recipe-maintainers:
    - ocefpaf
    - jsignell
